### ISSUE TITLE
Breakfast stuff

### ISSUE THREAD

**Issue by tomas-jimenez** [IntroToCode/Spring21_Recipes_Codemates13#1]
## 💬 Discussion topic

We need to incorporate the information in the breakfast readme

## ❗ Potential issues

Text

## 👥 People to consult

@mblairevans 

## 📃 Details

I think I would add french toasts!

**Comment by mblairevans** [comment]
Sounds good to me!

**Comment by donald-huang** [comment]
LGTM!
