### ISSUE TITLE
Dinner Recipe

### ISSUE THREAD

**Issue by donald-huang** [IntroToCode/Spring21_Recipes_Codemates13#6]
## 💬 Discussion topic

We need to add a dinner recipe.

## ❗ Potential issues

The team needs to agree on the recipe. 

## 👥 People to consult
@tomas-jimenez @mblairevans 

## 📃 Details

I think we should add spaghetti with tomato sauce to dinner!

**Comment by mblairevans** [comment]
Great recipe!
